name: API Manager Pull Request builder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build carbon-apimgt with Test.
      run: mvn clean install --file pom.xml -Dmaven.test.failure.ignore=true
      
    - name: Test Report
      uses: ScaCap/action-surefire-report@v1.0.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_if_no_tests: false
        report_paths: '**/tests-integration/tests-backend/target/surefire-reports/*.xml'
